version: "3.9"

services:
  web:
    build: .
    container_name: kontra_web
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET_KEY=devsecret
      - DATABASE_URL=sqlite:////data/dev.db
      - STARTUP_MONEY=3000
      - FLASK_ENV=development
    volumes:
      - .:/app
      - dbdata:/data

volumes:
  dbdata:
